import { chromium } from '/opt/node22/lib/node_modules/playwright/index.mjs';
const b = await chromium.launch({ executablePath:'/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const p = await b.newPage({ viewport:{width:1440,height:900} });
await p.goto('http://localhost:8642/index.html',{waitUntil:'load'});
await p.$eval('#member-stories', el=>el.scrollIntoView({behavior:'instant'}));
await p.waitForTimeout(1200);
await p.screenshot({path:'r17-vt-view.png'});
await p.click('.vt-card');
await p.waitForTimeout(800);
await p.screenshot({path:'r17-vt-lightbox.png'});
const m = await b.newPage({ viewport:{width:360,height:740} });
await m.goto('http://localhost:8642/index.html',{waitUntil:'load'});
await m.$eval('#member-stories', el=>el.scrollIntoView({behavior:'instant'}));
await m.waitForTimeout(1200);
await m.screenshot({path:'r17-vt-360.png'});
await m.click('.vt-card');
await m.waitForTimeout(800);
await m.screenshot({path:'r17-vt-lightbox-360.png'});
await b.close(); console.log('ok');
